/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ufes.trabalhodadosclima.view;

import javax.swing.JInternalFrame;
import javax.swing.JLabel;

/**
 *
 * @author tallesh
 */
public class UltimaAtualizacaoTempoView extends JInternalFrame {

    /**
     * Creates new form UltimaAtualizacaoTempoView
     */
    public UltimaAtualizacaoTempoView() {
        setVisible(true);
        setTitle("Último registro");
        initComponents();
    }

    public JLabel getDataLabel() {
        return lastDateLabel;
    }

    public JLabel getTempLabel() {
        return lastTempLabel;
    }
    
    public JLabel getPressureLabel() {
        return lastPressureLabel;
    }

    public JLabel getHumidityLabel() {
        return lastHumidityLabel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pressureTitle = new javax.swing.JLabel();
        tempTitle = new javax.swing.JLabel();
        humidityTitle = new javax.swing.JLabel();
        dataTitle = new javax.swing.JLabel();
        lastHumidityLabel = new javax.swing.JLabel();
        lastDateLabel = new javax.swing.JLabel();
        lastPressureLabel = new javax.swing.JLabel();
        lastTempLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pressureTitle.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        pressureTitle.setText("Pressão");

        tempTitle.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        tempTitle.setText("Temperatura");

        humidityTitle.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        humidityTitle.setText("Umidade");

        dataTitle.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        dataTitle.setText("Data");

        lastHumidityLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        lastHumidityLabel.setText("Umidade");

        lastDateLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        lastDateLabel.setText("DD/MM/AAA");

        lastPressureLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        lastPressureLabel.setText("Pressão");

        lastTempLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        lastTempLabel.setText("Temperatura");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dataTitle)
                    .addComponent(humidityTitle)
                    .addComponent(pressureTitle)
                    .addComponent(tempTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lastHumidityLabel)
                    .addComponent(lastPressureLabel)
                    .addComponent(lastTempLabel)
                    .addComponent(lastDateLabel))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lastTempLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(lastHumidityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(lastPressureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lastDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tempTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(humidityTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(pressureTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dataTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UltimaAtualizacaoTempoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UltimaAtualizacaoTempoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UltimaAtualizacaoTempoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UltimaAtualizacaoTempoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dataTitle;
    private javax.swing.JLabel humidityTitle;
    private javax.swing.JLabel lastDateLabel;
    private javax.swing.JLabel lastHumidityLabel;
    private javax.swing.JLabel lastPressureLabel;
    private javax.swing.JLabel lastTempLabel;
    private javax.swing.JLabel pressureTitle;
    private javax.swing.JLabel tempTitle;
    // End of variables declaration//GEN-END:variables
}
